import React, { useEffect, useState } from "react";
import type { DesktopState, RunDetail } from "./types";

export function RunHistory({ state }: { state: DesktopState }) {
  const [selected, setSelected] = useState<RunDetail>();
  const [summaries, setSummaries] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState("");
  useEffect(() => { let live = true; void Promise.all(state.runs.map(async (run) => { try { const detail = await window.codepilot.getRunDetail(run.id); return [run.id, detail.workers.find((worker) => worker.report?.summary)?.report?.summary ?? detail.summary?.review?.findings?.[0] ?? `Run ${run.status}.`] as const; } catch { return [run.id, `Run ${run.status}.`] as const; } })).then((items) => { if (live) setSummaries(Object.fromEntries(items)); }); return () => { live = false; }; }, [state.runs]);
  async function open(id: string) { setLoading(id); try { setSelected(await window.codepilot.getRunDetail(id)); } finally { setLoading(""); } }
  return <><div className="text-xs font-semibold uppercase tracking-[.2em] text-indigo-400">Mission control</div><h1 className="mt-2 text-2xl font-semibold">Agent sessions</h1><p className="mt-2 text-sm text-zinc-400">Open a session to see what was delivered, changed, tested, and flagged.</p><div className="mt-8 grid grid-cols-3 gap-4"><Stat label="Projects" value={state.projects.length} /><Stat label="Sessions" value={state.runs.length} /><Stat label="Needs review" value={state.runs.filter((run) => run.status === "needs_review").length} /></div><div className="mt-8 grid grid-cols-[minmax(320px,0.8fr)_minmax(0,1.2fr)] gap-6"><section className="h-fit overflow-hidden rounded-2xl border border-white/10 bg-white/[.025]">{state.runs.length ? state.runs.map((run) => <button key={run.id} onClick={() => void open(run.id)} className={`w-full border-b border-white/5 p-5 text-left hover:bg-white/5 ${selected?.id === run.id ? "bg-indigo-500/10" : ""}`}><div className="flex items-start justify-between gap-4"><span className="line-clamp-3 text-sm leading-5 text-zinc-200">{summaries[run.id] ?? "Loading result summary…"}</span><Status value={run.status} /></div><div className="mt-2 flex items-center justify-between gap-3"><span className="line-clamp-1 text-[10px] text-zinc-600">Task · {run.objective.split("\n")[0]}</span><span className="shrink-0 text-[10px] text-zinc-600">{new Date(run.createdAt).toLocaleString()}{loading === run.id ? " · loading…" : ""}</span></div></button>) : <div className="py-16 text-center text-sm text-zinc-600">No agent sessions yet.</div>}</section><section className="min-w-0">{selected ? <Detail run={selected} /> : <div className="rounded-2xl border border-dashed border-white/10 py-24 text-center text-sm text-zinc-600">Select a session to inspect its results.</div>}</section></div></>;
}
function Detail({ run }: { run: RunDetail }) { return <div className="space-y-4"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><div className="flex items-center justify-between"><Status value={run.status} /><span className="font-mono text-[10px] text-zinc-600">{run.id}</span></div><h2 className="mt-4 text-lg font-semibold">{run.objective}</h2></div>{run.workers.map((worker) => <div key={worker.taskId} className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold capitalize">{worker.provider} result</h3><Status value={worker.report?.status ?? worker.status} /></div>{worker.report ? <p className="mt-4 text-sm leading-6 text-zinc-300">{worker.report.summary}</p> : <p className="mt-4 text-sm text-zinc-500">No structured worker report was produced.</p>}{worker.verification?.resultCommit && <div className="mt-4 font-mono text-[10px] text-zinc-600">commit {worker.verification.resultCommit}</div>}</div>)}{run.summary?.review && <div className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><h3 className="text-sm font-semibold">Manager review · {run.summary.review.verdict}</h3><List items={run.summary.review.findings} /></div>}</div>; }
function List({ items }: { items: string[] }) { return items.length ? <div className="mt-3 space-y-1">{items.map((item, index) => <div key={`${item}-${index}`} className="text-xs leading-5 text-zinc-400">• {item}</div>)}</div> : null; }
function Status({ value }: { value: string }) { const good = ["completed", "ready", "passed"].includes(value), bad = ["failed", "rejected", "partial"].includes(value); return <span className={`shrink-0 rounded-md px-2 py-1 text-[10px] font-semibold uppercase tracking-wider ${good ? "bg-emerald-400/10 text-emerald-300" : bad ? "bg-red-400/10 text-red-300" : "bg-amber-400/10 text-amber-300"}`}>{value.replace("_", " ")}</span>; }
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="text-sm text-zinc-500">{label}</div><div className="mt-2 text-3xl font-semibold">{value}</div></div>; }
