import { execFile, spawn } from "node:child_process";
import { promisify } from "node:util";
import type { RunSummary } from "./domain.js";

const execFileAsync = promisify(execFile);
const MAX_PULL_REQUEST_BODY_CHARS = 60_000;

/** Build the durable run handoff that is sent directly to the hosting PR. */
export function buildPullRequestBody(objective: string, summary: RunSummary): string {
  const workers = summary.taskResults.map((result, index) => {
    const report = result.report;
    const changedPaths = result.verification.changedPaths
      .filter((path) => path !== ".codepilot-result.json")
      .slice(0, 100);
    return [
      `### ${index + 1}. ${result.externalId ?? result.taskId} · ${report?.status ?? "unreported"}`,
      safeMarkdown(report?.summary || "The worker did not provide a valid summary.", 2_000),
      `- Provider: ${result.provider}`,
      `- Process: ${result.verification.processExitCode === 0 ? "completed" : `exit ${result.verification.processExitCode}`}`,
      `- Commit: ${result.verification.resultCommit ? inlineCode(result.verification.resultCommit) : "None"}`,
      `- Changed paths: ${changedPaths.length ? changedPaths.map(inlineCode).join(", ") : "None"}`,
      report?.claimedTests.length
        ? `- Claimed checks: ${report.claimedTests.slice(0, 20).map((test) => inlineCode(compact(test, 500))).join(", ")}`
        : "- Claimed checks: None",
      report?.concerns.length ? `- Concerns: ${safeMarkdown(report.concerns.join("; "), 1_000)}` : undefined,
      report?.followUps.length ? `- Follow-ups: ${safeMarkdown(report.followUps.join("; "), 1_000)}` : undefined,
      result.warnings.length ? `- Coordinator warnings: ${safeMarkdown(result.warnings.join("; "), 1_000)}` : undefined,
    ].filter((line): line is string => Boolean(line)).join("\n").slice(0, 3_000);
  }).join("\n\n");
  const validations = summary.validations.length
    ? summary.validations.map((result) =>
        `- ${result.exitCode === 0 ? "✅" : "❌"} ${inlineCode(result.command)} (${result.durationMs} ms)`,
      ).join("\n")
    : "- Not run";
  const findings = summary.review.findings.length
    ? summary.review.findings.map((finding) => `- ${safeMarkdown(finding, 2_000)}`).join("\n")
    : "- No findings";
  const body = [
    "## Objective",
    safeMarkdown(objective, 4_000),
    "## Integration",
    `- Branch: \`${summary.integrationBranch ?? "none"}\``,
    `- Base commit: \`${summary.baseCommit}\``,
    `- Verdict: **${summary.review.verdict}**`,
    "## Agent work",
    workers || "No worker results were produced.",
    "## Validation",
    validations,
    "## Coordinator review",
    findings,
    "---",
    "Generated by codePilot from commit and validation evidence.",
  ].join("\n\n");
  return body.length <= MAX_PULL_REQUEST_BODY_CHARS
    ? body
    : `${body.slice(0, MAX_PULL_REQUEST_BODY_CHARS - 80)}\n\n_Description truncated by codePilot._`;
}

function compact(value: string, max: number): string {
  const normalized = value.replaceAll("\0", "").trim();
  return normalized.length <= max ? normalized : `${normalized.slice(0, max - 1)}…`;
}

function safeMarkdown(value: string, max: number): string {
  return compact(value, max)
    .replaceAll("@", "@\u200b")
    .replace(/\b(closes?|closed|fixes?|fixed|resolves?|resolved)(\s+#\d+)/gi, "$1\u200b$2");
}

function inlineCode(value: string): string {
  return `\`${compact(value, 1_000).replaceAll("`", "'")}\``;
}

export async function createGitHubPullRequest(
  repo: string,
  branch: string,
  objective: string,
  body: string,
  draft: boolean,
): Promise<string> {
  await execFileAsync("gh", ["--version"]);
  await execFileAsync("git", ["-C", repo, "push", "--set-upstream", "origin", branch]);
  const title = objective.split(/\r?\n/, 1)[0]!.trim().slice(0, 240) || "codePilot delivery";
  const args = [
    "pr",
    "create",
    "--head",
    branch,
    "--title",
    title,
    "--body-file",
    "-",
    ...(draft ? ["--draft"] : []),
  ];
  const stdout = await runWithInput("gh", args, repo, body);
  const url = stdout.trim().split(/\r?\n/).reverse().find((line: string) => /^https:\/\//.test(line));
  if (!url) throw new Error(`GitHub CLI did not return a pull request URL: ${stdout.trim()}`);
  return url;
}

async function runWithInput(command: string, args: string[], cwd: string, input: string): Promise<string> {
  return await new Promise((resolve, reject) => {
    const child = spawn(command, args, { cwd, shell: false, stdio: ["pipe", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk: Buffer) => { stdout += chunk.toString("utf8"); });
    child.stderr.on("data", (chunk: Buffer) => { stderr += chunk.toString("utf8"); });
    child.once("error", reject);
    child.once("close", (code) => {
      if (code === 0) resolve(stdout);
      else reject(new Error(`${command} exited with ${code ?? 1}: ${stderr.trim() || stdout.trim()}`));
    });
    child.stdin.end(input);
  });
}
